---

- name: Delete exists node_modules
  file: dest={{ app_path }}/node_modules state=absent 
   
- name: install npm packages
  npm: path={{ app_path }} 
  ignore_errors: yes
  


- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Start demo app."
  command: forever start {{ app_server_path }}
  when: "forever_list.stdout.find('{{ app_server_path }}') == -1"
  
- name: "Restart demo app."
  command: forever start {{ app_server_path }}
  when: "forever_list.stdout.find('{{ app_server_path }}') != -1"